# SPDX-FileCopyrightText: 2026 Pengfan Chang <support@swiphtgroup.com>
# SPDX-License-Identifier: GPL-3.0-only

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '02:00'
      timezone: Asia/Singapore
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: gradle
    directory: /ui/android
    schedule:
      interval: weekly
      day: monday
      time: '02:30'
      timezone: Asia/Singapore
    groups:
      android:
        patterns: ['*']

  - package-ecosystem: maven
    directory: /ui/javafx
    schedule:
      interval: weekly
      day: monday
      time: '02:45'
      timezone: Asia/Singapore
    groups:
      javafx-gluon:
        patterns: ['*']

  - package-ecosystem: swift
    directory: /ui/apple
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: Asia/Singapore
    groups:
      apple:
        patterns: ['*']
