# SPDX-FileCopyrightText: 2026 Pengfan Chang <support@swiphtgroup.com>
# SPDX-License-Identifier: GPL-3.0-only

ko_fi: jpfchang
liberapay: jpfchang
issuehunt: johnthre
custom:
  - https://nowpayments.io/donation?api_key=5792a927-dd7d-4b0c-982b-584a7499ffc9
